name: Unit Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
